title: Christianity in 24 Hours
description: The Bible tells one story. Humanity growing up.
remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme
  - jekyll-relative-links

relative_links:
  enabled: true

defaults:
  - scope:
      path: "manuscript"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"

exclude:
  - reference
  - OUTLINE.md
  - README.md
  - manuscript/Book.txt
  - manuscript/SAVED.md
